### Register a book
POST http://localhost:3000/api/v1/books/register
Content-Type: application/json

{
    "title": "The Lord of the Rings",
    "author": "J.R.R. Tolkien",
    "isbn": "978-3-16-148410-0"
}

### Borrow a book
POST http://localhost:3000/api/v1/books/borrow
Content-Type: application/json

{
  "bookId": "25cb755a-e049-46aa-a60b-155f28dc86ab",
  "readerId": "Alice"
}

### Return a book
POST http://localhost:3000/api/v1/books/return
Content-Type: application/json

{
  "bookId": "25cb755a-e049-46aa-a60b-155f28dc86ab",
  "condition": "bad"
}

### Repair a book
POST http://localhost:3000/api/v1/books/repair
Content-Type: application/json

{
  "bookId": "25cb755a-e049-46aa-a60b-155f28dc86ab",
  "comment": "Page pinned"
}

### Remove a book
POST http://localhost:3000/api/v1/books/remove
Content-Type: application/json

{
"bookId": "25cb755a-e049-46aa-a60b-155f28dc86ab",
"reason": "Book is unrepairable"
}

### Get a book
GET http://localhost:3000/api/v1/books/25cb755a-e049-46aa-a60b-155f28dc86ab
