### Register a book
POST http://localhost:3000/api/v1/books/register
Content-Type: application/json

{
    "title": "The Lord of the Rings",
    "author": "J.R.R. Tolkien",
    "isbn": "978-3-16-148410-0"
}

### Borrow a book
POST http://localhost:3000/api/v1/books/borrow
Content-Type: application/json

{
  "bookId": "ef069c76-7b9b-4ae9-9995-004f261523a8",
  "readerId": "Bob"
}

### Return a book
POST http://localhost:3000/api/v1/books/return
Content-Type: application/json

{
  "bookId": "ef069c76-7b9b-4ae9-9995-004f261523a8",
  "condition": "bad"
}

### Repair a book
POST http://localhost:3000/api/v1/books/repair
Content-Type: application/json

{
  "bookId": "ef069c76-7b9b-4ae9-9995-004f261523a8",
  "comment": "Page pinned"
}

### Remove a book
POST http://localhost:3000/api/v1/books/remove
Content-Type: application/json

{
"bookId": "ef069c76-7b9b-4ae9-9995-004f261523a8",
"reason": "Book is unrepairable"
}

### Get a book
GET http://localhost:3000/api/v1/books/ef069c76-7b9b-4ae9-9995-004f261523a8

### Get a book on Revision 2
GET http://localhost:3000/api/v1/books/ef069c76-7b9b-4ae9-9995-004f261523a8?revision=2

### Replay the last event
POST http://localhost:3000/api/v1/books/replay/ef069c76-7b9b-4ae9-9995-004f261523a8
