### Register a book
POST http://localhost:3000/api/v1/books/register
Content-Type: application/json

{
    "title": "The Lord of the Rings",
    "author": "J.R.R. Tolkien",
    "isbn": "978-3-16-148410-0"
}

### Borrow a book
POST http://localhost:3000/api/v1/books/borrow
Content-Type: application/json

{
  "bookId": "494f9ce9-f26d-42a5-a944-bf8d8d6a848b",
  "readerId": "Alice"
}

### Return a book
POST http://localhost:3000/api/v1/books/return
Content-Type: application/json

{
  "bookId": "52bc45a9-5b5a-499c-a740-ec935903d065",
  "condition": "bad"
}

### Repair a book
POST http://localhost:3000/api/v1/books/repair
Content-Type: application/json

{
  "bookId": "52bc45a9-5b5a-499c-a740-ec935903d065",
  "comment": "Page pinned"
}

### Remove a book
POST http://localhost:3000/api/v1/books/remove
Content-Type: application/json

{
"bookId": "52bc45a9-5b5a-499c-a740-ec935903d065",
"reason": "Book is unrepairable"
}

### Get a book
GET http://localhost:3000/api/v1/books/52bc45a9-5b5a-499c-a740-ec935903d065


### Replay the last event
POST http://localhost:3000/api/v1/books/replay/52bc45a9-5b5a-499c-a740-ec935903d065
